/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class VadUtil */

#ifndef _Included_VadUtil
#define _Included_VadUtil
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     VadUtil
 * Method:    create
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_VadUtil_create
  (JNIEnv *, jclass);

/*
 * Class:     VadUtil
 * Method:    free
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_VadUtil_free
  (JNIEnv *, jclass, jlong);

/*
 * Class:     VadUtil
 * Method:    reset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_VadUtil_reset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     VadUtil
 * Method:    setMode
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_VadUtil_setMode
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     VadUtil
 * Method:    setSampleRate
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_VadUtil_setSampleRate
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     VadUtil
 * Method:    process
 * Signature: (J[S)I
 */
JNIEXPORT jint JNICALL Java_VadUtil_process
  (JNIEnv *, jclass, jlong, jshortArray);

#ifdef __cplusplus
}
#endif
#endif
